#!/bin/bash
ecmin
scp ~/BOTBALL/Create/out/main.c root@192.168.125.1:"/home/root/Documents/KISS/Default\ User/botball-create/src/main.c"
ssh root@192.168.125.1 'gcc -I/home/root/Documents/KISS/Default\ User/botball-create/include -I/usr/local/include/include -Wall /home/root/Documents/KISS/Default\ User/botball-create/src/main.c /harrogate/apps/compiler/compilation-environments/c/_init_helper.c -L/usr/local/lib -lwallaby -lm -o /home/root/Documents/KISS/Default\ User/botball-create/bin/botball_user_program'
